### ISSUE TITLE
Table plug-in wb-tables class does not work in theme-gc-intranet?

### ISSUE THREAD

**Issue by Mercier** [wet-boew/theme-gc-intranet#137]
Trying  to apply the table plug-in: http://wet-boew.github.io/v4.0-ci/docs/ref/tables/tables-en.html to the latest version of the Government of Canada intranet theme. I use the table class="wb-tables table" but the sorting and filtering does not display. I used the same code in the Government of Canada Web Usability Theme and it works fine.  Another person on my team has the same issue. Thank you.

**Comment by pjackson28** [comment]
The code is working in the GC intranet theme here: http://wet-boew.github.io/themes-dist/theme-gc-intranet/demos/tables/tables-en.html

Perhaps some of the URLs for supporting files in your markup are incorrect. You should check the error console for any errors as well as check for any 404s.

**Comment by Mercier** [comment]
When we remove the list tags around the footer links, the sorting and filtering of the wb-tables stops working. When we put them back in, the sorting and filtering works again. And before you ask why we removed them, it was just temporary, but it definitely had a strange impact.

**Comment by pjackson28** [comment]
Were there any errors in the console? Did any of the JS files fail to load?
