### ISSUE TITLE
Government of Canada Intranet theme: Breadcrumb trail

### ISSUE THREAD

**Issue by juliemercier** [wet-boew/theme-gc-intranet#160]
Just curious as to why the breadcrumb trail on the Intranet theme and on the Usability theme show the current page title (unlinked), but on the Canada.ca theme, the breadcrumb trail does not include the current page title at all? Should we be working towards eliminating the current page title from the breadcrumb from all GC templates? What is the correct standard? How come this is not consistent across all templates? Thank you.

**Comment by shawnthompson** [comment]
This was a decision made by the Content and IA team just for the Canada.ca site. The site will be huge and the breadcrumbs will be very long. We've decided on breaking the standard with the GCWeb theme and to leave the other all the same. Might be revisiting this at a later date for all the other themes.

**Comment by juliemercier** [comment]
Thank you.
